### ISSUE TITLE
Access to gallery and the camera

### ISSUE THREAD

**Issue by nickimirani** [PeppeL-G/course-material#43]
# Client-Server Communication

# The problem
We would like our user to post a photo from their gallery or take a picture with their camera and upload it, but we are not sure where to start. Should we use additional APIs? And is this even possible for us or is it too hard to implement?

## question 1
How can we allow the user to take a picture with their camera and upload?

## question 2
How can we allow the user to access their gallery and choose a picture to upload?

## question 3
Is this possible for us to do?

**Comment by PeppeL-G** [comment]
It is possible to have file uploads in a REST API, but I recommend you to not implement it since it's not straight forward. Instead, I suggest you let the user enter a URL to image that already exists on the web (just right click on any image you want in a web browser and select "Copy Path", or similar), and you store that in your database with the rest of your resource. Then it's just an additional string (the URL) you need to handle.

And, if a user wants to use one of her own images, she can easily upload it to the web using One Drive or similar, and create a share link to it.
