### ISSUE TITLE
Login-Sessions

### ISSUE THREAD

**Issue by paulinewahle** [PeppeL-G/course-material#44]
In the tutorial RestAPI Basics you are mentioning login-sessions as uri. Should there be a database '/login-sessions' apart from '/accounts' that checks if user account attributes exist and are correct for a login (GET?) request to work?

**Comment by PeppeL-G** [comment]
Hi @paulinevah!

I'm not sure what you are referring to, but in your projects you should use Access Tokens to remember which account the user has logged in to. When logging in, the client will obtain the Access Token, and should then pass it along in all HTTP requests requiring authorization as a proof of having logged in to an account.

In your case, the Access Tokens should be implemented as JSON Web Tokens (JWT), and they are self-contained, so they will not be stored anywhere but on the client.

A login request should be a POST request (since the request is about _creating_ an Access Token).

// Peter L-G
