### ISSUE TITLE
How to update/edit and delete on backend

### ISSUE THREAD

**Issue by semikandiyoti** [PeppeL-G/course-material#46]
# Course
Client-Server Communication 2022

We used update and delete method in lab 2 but I don't really understand what to write in my backend, Should I write something in the backend like app.post. Also after the editing part, don't understand how to re-save it to the database.
My backend looks like this: 

app.get("/bookings", function(request, response){
	
	const query = "SELECT * FROM bookings"
	
	db.all(query, function(error, bookings){
		
		if(error){
			console.log(error)
			response.status(500).end()
		}else{
			response.status(200).json(bookings)
		}
		
	})
	
})

app.post('/bookings', function(request, response){

	const accessToken = request.get("Authorization")
	const payload = jsonwebtoken.verify(accessToken, "qwedsgsadsdsgssd")
	
	const city = request.body.city
	const date = request.body.date
	const time = request.body.time
	const reason = request.body.reason
	
	if(accountId != payload.accountId){
		response.status(401).end()
		return
	}
	
	const errorCodes = []
	
	
	if(0 < errorCodes.length){
		response.status(400).json(errorCodes)
	}else{
		
		const query = "INSERT INTO bookings (city, date, time, reason) VALUES (?, ?, ?, ?)"
		const values = [city, date, time, reason]
		
		db.run(query, values, function(error){
			if(error){
				console.log(error)
				response.status(500).end()
			}else{
				response.status(201).end()
			}
		})
		
	}
	
})

The second question, about the tokens, I did the tokens page according to the tutorial but I am not sure if its working correctly, also I am not sure the main reason we are doing it. My site was (and still is) working perfectly, why are we adding them?

https://prnt.sc/x3VE9q7u8LRz

(If) I did correctly, what should I see in this page: http://localhost:8080/tokens

**Comment by PeppeL-G** [comment]
>We used update and delete method in lab 2 but I don't really understand what to write in my backend
You should use the PUT and DELETE methods. See sample usage at:

https://peppel-g.github.io/course-material/lectures/rest-api-in-express/

There the resources are stored in an array. You store the resources in the database, so you need to send UPDATE and DELETE queries to the database when receiving these requests.

> I did the tokens page according to the tutorial but I am not sure if its working correctly

The line `if(accountId != payload.accountId){` should crash, because you have no variable named `accountId`. That is something the client should pass along in the body of the request (part of the resource).

>I am not sure the main reason we are doing it

We use access tokens to verify that users have logged in to an account before, and that they resources they try to create/update/delete are their own resources, and don't belong to someone else.
