### ISSUE TITLE
Authorisation GET identifying posts by accountId

### ISSUE THREAD

**Issue by paulinewahle** [PeppeL-G/course-material#49]
# Course
Client-Server Communication.

# The problem
(Backend) GET own projects with Authorisation. 
The following code is supposed to read the accountId from the accessToken to match to authorise for this activity. At the same time the accountId should identify the user and display her own projects. 
What went wrong here? 
<img width="1132" alt="Screenshot 2022-10-14 at 15 53 19" src="https://user-images.githubusercontent.com/80485598/195863971-141ff0b6-0d0a-4ae1-8633-0be3e1164a06.png">

The accessToken is being sent to the backend via Authorisation header: 
<img width="894" alt="Screenshot 2022-10-14 at 15 52 53" src="https://user-images.githubusercontent.com/80485598/195863882-3c6115bc-0235-4982-8227-3cc93a4704bc.png">

In the end, we expect to get a 401 Error when entering the /my-projects URL without being signed in. For now we only get a 500 server error. 

Without the verification steps in the backend, all projects get displayed normally. With them they disappear. 
<img width="488" alt="Screenshot 2022-10-14 at 15 57 09" src="https://user-images.githubusercontent.com/80485598/195864949-f7b654a7-dad3-4ebe-8abe-a4718335dab7.png">

**Comment by PeppeL-G** [comment]
To identify all projects that belongs to an account with id `5` , you should use the URI `/projects?accountId=5`. So in your code, you should use:

```js
const accountId = request.query.accountId
```

Then, since users should be able to only access their own projects (I imagine), you need to check that the user has logged in to the account with id 5 (in this example). So you need to retrieve the accountId from the access token, and see if it's the same as `request.query.accountId`. If they are not the same, then you don't allow the request to be carried out.

When you use `jwt.verify()` and you pass it an accessToken that is not valid (i.e. the user had tried to change it), or you use a different secret from when you created it, then an exception will be thrown, and Express will by default send back status code 500 when that happens. So optimally you should catch that exception and send back status code 401 instead, but you don't need to worry about that (I'm trying to make it easier for you by not introducing try and catch statements ^^').

**Comment by tuvapersson** [comment]
Hi again Peter, thank you for the response. We have tried to implement what you suggested, unfortunately with no further success. Here is our new code. 

We checked so that the jwt secret is the same when it is being created. Is the if statement correct? Will the URI be correct if we do it this way i.e. be /projects?accountId=(accountId) ?

Can you see if anything is missing or if anything looks wrong?

![Screenshot 2022-10-16 at 17 09 16](https://user-images.githubusercontent.com/80885269/196043128-016a9aef-2c34-4
![Screenshot 2022-10-16 at 17 09 30](https://user-images.githubusercontent.com/80885269/196043139-034c93f9-93a2-4f0e-93cf-cc63ae7cf5da.png)
5af-9b10-2afa9b35b4d5.png)

**Comment by tuvapersson** [comment]
![Screenshot 2022-10-16 at 17 30 48](https://user-images.githubusercontent.com/80885269/196044013-b7642112-7cf9-4b82-b089-64718908c7f5.png)


Here is app.js. Went wrong when uploading it before.

**Comment by paulinewahle** [comment]
Since we can not actually use the query /projects?accountId=x as a fetch path? Therefore, request.query.accountId can't work. Instead the accountId should be detected by the user which has logged in. This info is accessible in the frontend inside the user Object. In what way can we pass in to the backend (via accessToken/idToken)?

**Comment by paulinewahle** [comment]
Similar, close related problem occurs when we want to **get** accounts **where** the accountId from the accessToken is identical to the id of the account. The accountId should be extracted from "Authorization" header in the frontend? How can the when condition access the accounts.id?
<img width="1438" alt="Screenshot 2022-10-16 at 19 12 14" src="https://user-images.githubusercontent.com/80485598/196048751-079b271d-2f19-4d1b-b197-2f9ad439783d.png">

**Comment by PeppeL-G** [comment]
Hi!

When the `accountId` is used for filtering which projects that should be sent back, it should preferably be passed as a query string parameter. When using `fetch()`, use the URI `"http://localhost:3000/projects?accountId="+this.user.accountId` (or whatever you call call the property storing the id of the logged in account). Also pass along the user's access token in the `Authorization` header. Then, in your `app.get('/projects', ...)` handler, use `request.query.accountId` to obtain the actual value for the account id. Also open up your access token, and check if the account id there is the same as `request.query.accountId`.

>close related problem occurs when we want to get accounts where the accountId from the accessToken is identical to the id of the account.

When the request is about getting a resource with a specific id, one typically use GET `/accounts/:id` (e.g. `/accounts/45`). To obtain the actual id, you can use `request.params.id`.

// Peter L-G

**Comment by paulinewahle** [comment]
We've got it! Thank you! The formulation of the URI fetch() was is it that we didn't know and it solved everything
