### ISSUE TITLE
Google API login code error on Postman

### ISSUE THREAD

**Issue by liislepler** [PeppeL-G/course-material#51]
# Course
Client-Server Communication.

# The problem
When POSTing the Google authorization code on Postman for https://www.googleapis.com/oauth2/v4/token it shows "error": "unsupported_grant_type" "error_description": "Invalid grant_type: ".

![postman](https://user-images.githubusercontent.com/74419651/196446590-3182eefb-910d-4008-9d73-3fe76e34fad9.png)
![postman2](https://user-images.githubusercontent.com/74419651/196448727-c244c3db-8395-4a08-86bc-fe9fc4bc0dd6.png)

The information I got from Google API 
![google](https://user-images.githubusercontent.com/74419651/196446615-8b0c0414-3fbd-41d1-b41b-37f7c65bd7f3.png)

Everything works when opening the link which redirects to the Google login page, I can login and it directs me to my website but on Postman it gives an error. I checked many times with different Client IDs, Client secrets and different Google accounts but it's still the same error.

**Comment by PeppeL-G** [comment]
I'm guessing the error is that you have written `grant_type=authorization_code` on a new line. Most likely all of the query string parameters must be written on the same line.

**Comment by liislepler** [comment]
Yes! Now it works. Another question though, where in the code should I read out the body (the same code in Postman)? Is the third-party authentication passed together in app.post('/tokens', function(request, response) { }? Or should it be separate?

**Comment by PeppeL-G** [comment]
When the user has been redirected back from Google to the frontend, you should in the frontend send the `authorization_code` to the backend to login (the backend will trade it for an ID Token that contains the user's Google ID). That request you send to your backend can preferably be POST `/tokens` (since the request is about creating an access token and an id token using the `authorization_code`. So when receiving the POST `/tokens` request, you need to check whether you receive a username and a password, or an `authorization_code`, and then act accordingly.
