### ISSUE TITLE
Third party authorisation - connection to frontend

### ISSUE THREAD

**Issue by MartaSmb** [PeppeL-G/course-material#52]
Client-Server Communication.

We are able to access our google login page through localhost using express and node.js. We are stuck when it comes to trying to connect it to the front end and redirect users to the right URIs. Is there a standard way this can be done and do you have some pointers on what we should do next?
We used npm packages: passport and passport-google-oauth2

**Our google log in opens when we go to the URI we created: HTTP://localhost:3000/auth/google

This is the method we started writing to redirect us to the google login page:
```js
   googleSignIn() {
            fetch("http://localhost:3000/auth/google").then((response) => {
                if (response.status == 200) {
                    console.log("GET request worked status code 200")
                } else if (response.status == 500) {
                    console.log("GET request failed miserably status code 500")
                }
            });
        }
```

This is how we handled the GET request in the backend:
```js
app.get("/auth/google", 
  passport.authenticate("google", {scope: ["profile"]})
)
```

This is how the client id and secret are coming together (we don't know if this is relevant, but it's just how the package works (we took it from their documentation))
```js
const passport = require("passport")

const GoogleStrategy = require( 'passport-google-oauth2' ).Strategy;

const GOOGLE_CLIENT_ID = "extrodinery-id"
const GOOGLE_SECRET = "amazing-secret"

passport.use(new GoogleStrategy({
    clientID: GOOGLE_CLIENT_ID,
    clientSecret: GOOGLE_SECRET,
    callbackURL: "http://localhost:3000/auth/google/callback",
    passReqToCallback: true
  },
  function(request, accessToken, refreshToken, profile, done) {
  
      return done(null, profile);
   /* here we will later look for the user in the database or create a new one, for now, it is just sending back the whole profile*/
  }
));

passport.serializeUser(function(user,done){
    done(null,user)
})
passport.deserializeUser(function(user,done){
    done(null,user)
})
```

**Comment by PeppeL-G** [comment]
Hi!

I have no experience of using `passport` and `passport-google-oauth2` myself, so I'm afraid I can't help you with those. But, I'll try to help with the other stuff.

> This is the method we started writing to redirect us to the google login page:

That seems wrong. When you use `fetch()`, you tell the web browser to send an HTTP request in the background. The user will still stay on the same page as before. To redirect the user to the Google login page, you should rather use `window.location.href = "the-google-login-page.com"`, or simply use an anchor element the user can click on in the frontend to get there.

When the user has logged in on Google's own login page, the user should be redirected back to your frontend, where you receive the `code`. The `code` you should then send to your backend instead of username and password. When your backend receives the `code`, it should send it to Google to trade it for an ID Token, from which you can read out the user's Google ID (from the `sub` claim).

I'm not sure if Passport supports Google login in REST API:s. It can be that Passport only supports Google login on traditional websites.

I think the following page covers the requests you need to send:

https://developers.google.com/identity/openid-connect/openid-connect

About the *Create an anti-forgery state token* sub-chapter there: in your case you can make it a bit easier for you and skip verifying the anti-forgery token. Simply hard-code and re-use one and the same anti-forgery token you use that you send in the first request to Google, like `abcdeabcdeabcdeabcdeabcdeabcdeab`.

It might be that Google has a check and won't accept re-using the same anti-forgery token, and in those cases you need to dynamically generate one. In such case you can use something like this to generate a new random anti-forgery token each time:

https://stackoverflow.com/questions/1349404/generate-random-string-characters-in-javascript

// Peter L-G

**Comment by MartaSmb** [comment]
Heej! thank you for your feedback. Changing the fetch to window.location.href worked perfectly. 

The thing is Passport does the whole exchanging of code and ID tokens for us, so it is precoded. 

The code works now to a point of logging in. When we need to get user information from google (passport) we don't know how to access it and save it in our database. I'm guessing this has to do with Passport itself. This is our current code just in case it makes any sense and if you have an idea how to get to the user information. 
(passport uses "user.placeholder-to-access-information" to access specific parts of the profile. e.g. user.name, user.birthday etc.)

We would like to have something like this to retrieve the information, we just don't know if this is the right way to write it and where should we put it:

`/*...*/function(request, response){
  const user = request.user.displayName 
  response.json(user)
}`

This is how we use Passport to log in:

```//LOG IN WITH GOOGLE
app.get("/auth/google", 
  passport.authenticate("google", {scope: ["profile"]})
)

//RESPONSE GOOGLE
app.get("/auth/google/callback", passport.authenticate("google", {
  successRedirect: "http://127.0.0.1:5173/feed",
  failureRedirect: "http://127.0.0.1:5173/"
}))

//logout
app.get("/logout", function (req, res){
  req.logout()
  res.session.destroy();
})
```

This is how we enable usage of sessions and the "isLoggedIn" function would be used as a middleware to allow users to view pages only when they are logged in (we also don't really know if this is the best way for us to do authorization)

```function isLoggedIn(req, res, next){
  req.user ? next() : res.sendStatus(401)
}

app.use(session({secret: "cats", resave: false, saveUninitialized: true}))

app.use(passport.initialize())
app.use(passport.session())
```

**Comment by PeppeL-G** [comment]
I don't know how `passport` works, nor how it is meant to be used, and when looking at your code, I can't spot any obvious error, so I'm afraid I can't help you.

However, you seem to add support for sessions, but your REST API should not use sessions, but Access Tokens instead. So you might be going down a bad road here.
